# This file was generated by jschema_to_python version $js2p_version$.

import attr


@attr.s
class OptionalProperty(object):
    optional_property = attr.ib(default=42, metadata={"schema_property_name": "optionalProperty"})
