# This file was generated by jschema_to_python version $js2p_version$.

import attr


@attr.s
class RequiredProperty(object):
    required_property = attr.ib(metadata={"schema_property_name": "requiredProperty"})
