# This file was generated by jschema_to_python version $js2p_version$.

import dataclasses
from __future__ import annotations


@dataclasses.dataclass
class TestClass(object):
    """This is a test class."""

    required_property: int = dataclasses.field(metadata={"schema_property_name": "requiredProperty"})
    optional_property: int = dataclasses.field(default=42, metadata={"schema_property_name": "optionalProperty"})
