# This file was generated by jschema_to_python version $js2p_version$.

import attr


@attr.s
class TestClass(object):
    """This is a test class."""

    required_property = attr.ib(metadata={"schema_property_name": "requiredProperty"})
    optional_property = attr.ib(default=42, metadata={"schema_property_name": "optionalProperty"})
